apiVersion: v1
kind: Service
metadata:
  name: complete-production-e2e-deployment
  labels:
    app: complete-production-e2e-app
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: complete-production-e2e-app
